# PANDAS

In [1]:
import numpy as np 
import pandas as pd

In [2]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [3]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [6]:
df.to_csv('F20file1.csv')

In [7]:
df.to_csv('F20file2.csv',index=False)

In [8]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [9]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [10]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [11]:
z=pd.read_csv('F20file3.csv')
z

   Unnamed: 0   name generations Country
0           0   F-22         5th     USA
1           1  SU-57         5th  Russia
2           2   J-20         5th   China
3           3   F-35         5th     USA

In [12]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [13]:
z['name'][0]

'F-22'

In [19]:
z['name'][0]='F-47'

C:\Users\anubh\AppData\Local\Temp\ipykernel_15676\313757094.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  z['name'][0]='F-47'

In [17]:
z

   Unnamed: 0   name generations Country
0           0   F-22         5th     USA
1           1  SU-57         5th  Russia
2           2   J-20         5th   China
3           3   F-35         5th     USA