# PANDAS

In [1]:
import numpy as np 
import pandas as pd

In [2]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [3]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [4]:
df.to_csv('F20file1.csv')

In [5]:
df.to_csv('F20file2.csv',index=False)

In [6]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [7]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [8]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [9]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [10]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [11]:
z['name'][0]

'F-22'

In [12]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [13]:
#z.to_csv('F20file3.csv')

In [14]:
ser=pd.Series(np.random.rand(10))
ser

0    0.080935
1    0.304344
2    0.655446
3    0.524377
4    0.391233
5    0.909315
6    0.227568
7    0.506534
8    0.972232
9    0.996806
dtype: float64

In [15]:
type(ser)

pandas.Series

In [16]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.956076  0.114123  0.401718  0.532463  0.366837
1  0.268743  0.768963  0.421179  0.135056  0.223333
2  0.526444  0.923561  0.329152  0.843850  0.192361
3  0.811610  0.645048  0.256819  0.404141  0.314526
4  0.970014  0.522811  0.608624  0.669354  0.615757

In [17]:
type(newdf)

pandas.DataFrame

In [18]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.481269    0.505161    0.496483    0.506221    0.468109
std      0.294614    0.300387    0.271043    0.296341    0.291579
min      0.004679    0.000792    0.008138    0.001741    0.007313
25%      0.246700    0.211702    0.261839    0.213490    0.189970
50%      0.453530    0.517426    0.487933    0.515989    0.480154
75%      0.753471    0.741411    0.721775    0.786343    0.715667
max      0.993056    0.999897    0.997640    0.999425    0.999413

In [19]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [20]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [21]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [23]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [24]:
newdf.to_numpy()

array([['groot', 0.11412344855906542, 0.40171784642207187,
        0.5324634616470504, 0.36683716037615066],
       [0.2687431396874135, 0.7689629985732133, 0.42117870791393963,
        0.13505602503594494, 0.2233332810507085],
       [0.5264440734560721, 0.9235612116980819, 0.32915222657563836,
        0.8438501852233854, 0.1923614287967651],
       ...,
       [0.4114407674305406, 0.06340296512588373, 0.2034924544577611,
        0.964807443516093, 0.710998413009882],
       [0.10991959385708339, 0.8117892326903929, 0.38659650542731516,
        0.31250112439107136, 0.22626200973389898],
       [0.8230435949567255, 0.47259661978645773, 0.7098909386859589,
        0.8437424069919344, 0.09271934541516813]],
      shape=(334, 5), dtype=object)

In [25]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.268743,0.526444,0.81161,0.970014,0.785513,0.857356,0.120524,0.063562,0.499849,...,0.974641,0.427464,0.202525,0.051764,0.866791,0.502028,0.019478,0.411441,0.10992,0.823044
1,0.114123,0.768963,0.923561,0.645048,0.522811,0.645146,0.970737,0.275071,0.157707,0.679216,...,0.56743,0.060859,0.429915,0.641002,0.813599,0.113553,0.899645,0.063403,0.811789,0.472597
2,0.401718,0.421179,0.329152,0.256819,0.608624,0.008138,0.184614,0.281499,0.896382,0.30449,...,0.617468,0.12207,0.175569,0.231631,0.326127,0.587469,0.408318,0.203492,0.386597,0.709891
3,0.532463,0.135056,0.84385,0.404141,0.669354,0.905713,0.348414,0.847412,0.158867,0.347296,...,0.143148,0.757388,0.869323,0.355389,0.35715,0.218052,0.43663,0.964807,0.312501,0.843742
4,0.366837,0.223333,0.192361,0.314526,0.615757,0.972102,0.563377,0.182603,0.582705,0.402639,...,0.616534,0.032167,0.888428,0.812807,0.098425,0.159088,0.294182,0.710998,0.226262,0.092719

In [26]:
newdf.head()

          0         1         2         3         4
0     groot  0.114123  0.401718  0.532463  0.366837
1  0.268743  0.768963  0.421179  0.135056  0.223333
2  0.526444  0.923561  0.329152  0.843850  0.192361
3   0.81161  0.645048  0.256819  0.404141  0.314526
4  0.970014  0.522811  0.608624  0.669354  0.615757

In [27]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.823044  0.472597  0.709891  0.843742  0.092719
332   0.10992  0.811789  0.386597  0.312501  0.226262
331  0.411441  0.063403  0.203492  0.964807  0.710998
330  0.019478  0.899645  0.408318  0.436630  0.294182
329  0.502028  0.113553  0.587469  0.218052  0.159088
..        ...       ...       ...       ...       ...
4    0.970014  0.522811  0.608624  0.669354  0.615757
3     0.81161  0.645048  0.256819  0.404141  0.314526
2    0.526444  0.923561  0.329152  0.843850  0.192361
1    0.268743  0.768963  0.421179  0.135056  0.223333
0       groot  0.114123  0.401718  0.532463  0.366837

[334 rows x 5 columns]

In [28]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.366837  0.532463  0.401718  0.114123     groot
1    0.223333  0.135056  0.421179  0.768963  0.268743
2    0.192361  0.843850  0.329152  0.923561  0.526444
3    0.314526  0.404141  0.256819  0.645048   0.81161
4    0.615757  0.669354  0.608624  0.522811  0.970014
..        ...       ...       ...       ...       ...
329  0.159088  0.218052  0.587469  0.113553  0.502028
330  0.294182  0.436630  0.408318  0.899645  0.019478
331  0.710998  0.964807  0.203492  0.063403  0.411441
332  0.226262  0.312501  0.386597  0.811789   0.10992
333  0.092719  0.843742  0.709891  0.472597  0.823044

[334 rows x 5 columns]

In [29]:
newdf[0]

0         groot
1      0.268743
2      0.526444
3       0.81161
4      0.970014
         ...
329    0.502028
330    0.019478
331    0.411441
332     0.10992
333    0.823044
Name: 0, Length: 334, dtype: object

In [30]:
type(newdf[0])

pandas.Series

In [31]:
newdf2=newdf.copy()

In [32]:
newdf.loc[0,0] = 95

In [33]:
newdf

            0         1         2         3         4
0          95  0.114123  0.401718  0.532463  0.366837
1    0.268743  0.768963  0.421179  0.135056  0.223333
2    0.526444  0.923561  0.329152  0.843850  0.192361
3     0.81161  0.645048  0.256819  0.404141  0.314526
4    0.970014  0.522811  0.608624  0.669354  0.615757
..        ...       ...       ...       ...       ...
329  0.502028  0.113553  0.587469  0.218052  0.159088
330  0.019478  0.899645  0.408318  0.436630  0.294182
331  0.411441  0.063403  0.203492  0.964807  0.710998
332   0.10992  0.811789  0.386597  0.312501  0.226262
333  0.823044  0.472597  0.709891  0.843742  0.092719

[334 rows x 5 columns]

In [34]:
newdf.loc[0,0]=980
newdf.head(7)

          0         1         2         3         4
0       980  0.114123  0.401718  0.532463  0.366837
1  0.268743  0.768963  0.421179  0.135056  0.223333
2  0.526444  0.923561  0.329152  0.843850  0.192361
3   0.81161  0.645048  0.256819  0.404141  0.314526
4  0.970014  0.522811  0.608624  0.669354  0.615757
5  0.785513  0.645146  0.008138  0.905713  0.972102
6  0.857356  0.970737  0.184614  0.348414  0.563377

In [35]:
newdf.columns=list("ABCDE")
newdf

            A         B         C         D         E
0         980  0.114123  0.401718  0.532463  0.366837
1    0.268743  0.768963  0.421179  0.135056  0.223333
2    0.526444  0.923561  0.329152  0.843850  0.192361
3     0.81161  0.645048  0.256819  0.404141  0.314526
4    0.970014  0.522811  0.608624  0.669354  0.615757
..        ...       ...       ...       ...       ...
329  0.502028  0.113553  0.587469  0.218052  0.159088
330  0.019478  0.899645  0.408318  0.436630  0.294182
331  0.411441  0.063403  0.203492  0.964807  0.710998
332   0.10992  0.811789  0.386597  0.312501  0.226262
333  0.823044  0.472597  0.709891  0.843742  0.092719

[334 rows x 5 columns]

In [36]:
newdf.loc[0,0]=990

In [37]:
newdf.head()

          A         B         C         D         E      0
0       980  0.114123  0.401718  0.532463  0.366837  990.0
1  0.268743  0.768963  0.421179  0.135056  0.223333    NaN
2  0.526444  0.923561  0.329152  0.843850  0.192361    NaN
3   0.81161  0.645048  0.256819  0.404141  0.314526    NaN
4  0.970014  0.522811  0.608624  0.669354  0.615757    NaN

In [38]:
newdf = newdf.drop(0, axis=1)
newdf.head()

          A         B         C         D         E
0       980  0.114123  0.401718  0.532463  0.366837
1  0.268743  0.768963  0.421179  0.135056  0.223333
2  0.526444  0.923561  0.329152  0.843850  0.192361
3   0.81161  0.645048  0.256819  0.404141  0.314526
4  0.970014  0.522811  0.608624  0.669354  0.615757

In [39]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.421179  0.135056
2  0.329152  0.843850

In [40]:
newdf.loc[:,['C','D']]

            C         D
0    0.401718  0.532463
1    0.421179  0.135056
2    0.329152  0.843850
3    0.256819  0.404141
4    0.608624  0.669354
..        ...       ...
329  0.587469  0.218052
330  0.408318  0.436630
331  0.203492  0.964807
332  0.386597  0.312501
333  0.709891  0.843742

[334 rows x 2 columns]

In [41]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.268743  0.768963  0.421179  0.135056  0.223333
2  0.526444  0.923561  0.329152  0.843850  0.192361

In [42]:
newdf.loc[(newdf['A']<0.3)&(newdf['C']>0.1)]

            A         B         C         D         E
1    0.268743  0.768963  0.421179  0.135056  0.223333
7    0.120524  0.275071  0.281499  0.847412  0.182603
8    0.063562  0.157707  0.896382  0.158867  0.582705
11   0.107831  0.169892  0.479757  0.083623  0.995286
12   0.039473  0.673971  0.924029  0.160349  0.660412
..        ...       ...       ...       ...       ...
322  0.028711  0.626646  0.421874  0.926800  0.107762
326  0.202525  0.429915  0.175569  0.869323  0.888428
327  0.051764  0.641002  0.231631  0.355389  0.812807
330  0.019478  0.899645  0.408318  0.436630  0.294182
332   0.10992  0.811789  0.386597  0.312501  0.226262

[103 rows x 5 columns]

In [43]:
newdf.iloc[0,4]

np.float64(0.36683716037615066)

In [44]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.114123  0.401718
1  0.768963  0.421179

In [45]:
newdf.head(3)

          A         B         C         D         E
0       980  0.114123  0.401718  0.532463  0.366837
1  0.268743  0.768963  0.421179  0.135056  0.223333
2  0.526444  0.923561  0.329152  0.843850  0.192361

In [46]:
newdf.drop([0])

            A         B         C         D         E
1    0.268743  0.768963  0.421179  0.135056  0.223333
2    0.526444  0.923561  0.329152  0.843850  0.192361
3     0.81161  0.645048  0.256819  0.404141  0.314526
4    0.970014  0.522811  0.608624  0.669354  0.615757
5    0.785513  0.645146  0.008138  0.905713  0.972102
..        ...       ...       ...       ...       ...
329  0.502028  0.113553  0.587469  0.218052  0.159088
330  0.019478  0.899645  0.408318  0.436630  0.294182
331  0.411441  0.063403  0.203492  0.964807  0.710998
332   0.10992  0.811789  0.386597  0.312501  0.226262
333  0.823044  0.472597  0.709891  0.843742  0.092719

[333 rows x 5 columns]

In [47]:
newdf.drop(['A','C'],axis=1)

            B         D         E
0    0.114123  0.532463  0.366837
1    0.768963  0.135056  0.223333
2    0.923561  0.843850  0.192361
3    0.645048  0.404141  0.314526
4    0.522811  0.669354  0.615757
..        ...       ...       ...
329  0.113553  0.218052  0.159088
330  0.899645  0.436630  0.294182
331  0.063403  0.964807  0.710998
332  0.811789  0.312501  0.226262
333  0.472597  0.843742  0.092719

[334 rows x 3 columns]

In [48]:
newdf.drop(['D','E'],axis=1, inplace=True)

In [49]:
newdf

            A         B         C
0         980  0.114123  0.401718
1    0.268743  0.768963  0.421179
2    0.526444  0.923561  0.329152
3     0.81161  0.645048  0.256819
4    0.970014  0.522811  0.608624
..        ...       ...       ...
329  0.502028  0.113553  0.587469
330  0.019478  0.899645  0.408318
331  0.411441  0.063403  0.203492
332   0.10992  0.811789  0.386597
333  0.823044  0.472597  0.709891

[334 rows x 3 columns]

In [50]:
newdf.reset_index(drop=True, inplace=True)
newdf.head(3)

          A         B         C
0       980  0.114123  0.401718
1  0.268743  0.768963  0.421179
2  0.526444  0.923561  0.329152

In [51]:
newdf['B']=None

In [52]:
newdf

            A     B         C
0         980  None  0.401718
1    0.268743  None  0.421179
2    0.526444  None  0.329152
3     0.81161  None  0.256819
4    0.970014  None  0.608624
..        ...   ...       ...
329  0.502028  None  0.587469
330  0.019478  None  0.408318
331  0.411441  None  0.203492
332   0.10992  None  0.386597
333  0.823044  None  0.709891

[334 rows x 3 columns]

In [53]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
329    True
330    True
331    True
332    True
333    True
Name: B, Length: 334, dtype: bool

In [54]:
newdf.loc[:,['B']]=90
newdf

            A   B         C
0         980  90  0.401718
1    0.268743  90  0.421179
2    0.526444  90  0.329152
3     0.81161  90  0.256819
4    0.970014  90  0.608624
..        ...  ..       ...
329  0.502028  90  0.587469
330  0.019478  90  0.408318
331  0.411441  90  0.203492
332   0.10992  90  0.386597
333  0.823044  90  0.709891

[334 rows x 3 columns]

In [55]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       334 non-null    object
 1   B       334 non-null    object
 2   C       334 non-null    float64
dtypes: float64(1), object(2)
memory usage: 8.0+ KB

In [56]:
newdf.notnull()

        A     B     C
0    True  True  True
1    True  True  True
2    True  True  True
3    True  True  True
4    True  True  True
..    ...   ...   ...
329  True  True  True
330  True  True  True
331  True  True  True
332  True  True  True
333  True  True  True

[334 rows x 3 columns]

In [ ]:
import open
data=pd.read_excel('F20file4.xlsx')

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.