# PANDAS

In [4]:
import numpy as np 
import pandas as pd

In [5]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [6]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [7]:
df.to_csv('F20file1.csv')

In [8]:
df.to_csv('F20file2.csv',index=False)

In [9]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [10]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [11]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [12]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [13]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [14]:
z['name'][0]

'F-22'

In [15]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [16]:
z.to_csv('F20file3.csv')

PermissionError: [Errno 13] Permission denied: 'F20file3.csv'

In [ ]:
ser=pd.Series(np.random.rand(10))
ser

0    0.349345
1    0.448532
2    0.436258
3    0.479489
4    0.636410
5    0.351227
6    0.908611
7    0.019150
8    0.087708
9    0.431888
dtype: float64

In [ ]:
type(ser)

NameError: name 'ser' is not defined

In [ ]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

NameError: name 'pd' is not defined