# PANDAS

In [1]:
import numpy as np 
import pandas as pd

In [2]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [3]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [4]:
df.to_csv('F20file1.csv')

In [5]:
df.to_csv('F20file2.csv',index=False)

In [6]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [7]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [8]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [9]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [10]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [11]:
z['name'][0]

'F-22'

In [12]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [13]:
#z.to_csv('F20file3.csv')

In [14]:
ser=pd.Series(np.random.rand(10))
ser

0    0.251779
1    0.221117
2    0.983020
3    0.305336
4    0.751689
5    0.695128
6    0.350485
7    0.928155
8    0.331123
9    0.936278
dtype: float64

In [15]:
type(ser)

pandas.Series

In [16]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.487753  0.511122  0.273547  0.867901  0.994996
1  0.953755  0.982297  0.458345  0.805434  0.739970
2  0.828743  0.637125  0.752267  0.714775  0.937870
3  0.682883  0.300200  0.214938  0.305622  0.470067
4  0.095020  0.996165  0.921691  0.649134  0.787123

In [17]:
type(newdf)

pandas.DataFrame

In [18]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.511298    0.500001    0.527845    0.501810    0.507095
std      0.289407    0.288839    0.272602    0.285443    0.280970
min      0.000205    0.000842    0.003046    0.000031    0.006695
25%      0.281088    0.261549    0.308314    0.253095    0.288743
50%      0.496198    0.519385    0.539932    0.501697    0.505065
75%      0.765071    0.756339    0.745679    0.739302    0.754299
max      0.998270    0.996165    0.997684    0.996630    0.994996

In [19]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [20]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [21]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [23]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [24]:
newdf.to_numpy()

array([['groot', 0.5111219338358878, 0.27354694969294513,
        0.8679006524670521, 0.9949956102916867],
       [0.9537551872084095, 0.9822970822120192, 0.4583450231362005,
        0.8054339091869276, 0.739969587853283],
       [0.8287425514206274, 0.6371245083258767, 0.7522671342237645,
        0.7147746246052257, 0.9378696796228497],
       ...,
       [0.4441786987945092, 0.7099382804151473, 0.6332005143096704,
        0.8391484517249483, 0.5969845247037328],
       [0.7724520000055134, 0.46876607306242435, 0.5017604806830178,
        0.9946791884699359, 0.5182008821780055],
       [0.20023271792633768, 0.5308379676305109, 0.10754343718813131,
        0.7821512736742482, 0.6453538390124374]],
      shape=(334, 5), dtype=object)

In [25]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.953755,0.828743,0.682883,0.09502,0.799055,0.288879,0.542626,0.297316,0.644033,...,0.903777,0.450002,0.496431,0.48623,0.882716,0.768136,0.605076,0.444179,0.772452,0.200233
1,0.511122,0.982297,0.637125,0.3002,0.996165,0.606201,0.853872,0.531961,0.414484,0.486879,...,0.804547,0.851228,0.608815,0.172463,0.386652,0.396553,0.73097,0.709938,0.468766,0.530838
2,0.273547,0.458345,0.752267,0.214938,0.921691,0.624845,0.945271,0.363045,0.535699,0.407832,...,0.675981,0.163138,0.58821,0.504783,0.902335,0.792386,0.276145,0.633201,0.50176,0.107543
3,0.867901,0.805434,0.714775,0.305622,0.649134,0.259708,0.273697,0.302955,0.342217,0.580978,...,0.805323,0.238701,0.835755,0.903873,0.906869,0.520564,0.136945,0.839148,0.994679,0.782151
4,0.994996,0.73997,0.93787,0.470067,0.787123,0.627978,0.501682,0.067026,0.310022,0.243355,...,0.809558,0.405984,0.549799,0.733632,0.565124,0.456191,0.291497,0.596985,0.518201,0.645354

In [26]:
newdf.head()

          0         1         2         3         4
0     groot  0.511122  0.273547  0.867901  0.994996
1  0.953755  0.982297  0.458345  0.805434  0.739970
2  0.828743  0.637125  0.752267  0.714775  0.937870
3  0.682883  0.300200  0.214938  0.305622  0.470067
4   0.09502  0.996165  0.921691  0.649134  0.787123

In [27]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.200233  0.530838  0.107543  0.782151  0.645354
332  0.772452  0.468766  0.501760  0.994679  0.518201
331  0.444179  0.709938  0.633201  0.839148  0.596985
330  0.605076  0.730970  0.276145  0.136945  0.291497
329  0.768136  0.396553  0.792386  0.520564  0.456191
..        ...       ...       ...       ...       ...
4     0.09502  0.996165  0.921691  0.649134  0.787123
3    0.682883  0.300200  0.214938  0.305622  0.470067
2    0.828743  0.637125  0.752267  0.714775  0.937870
1    0.953755  0.982297  0.458345  0.805434  0.739970
0       groot  0.511122  0.273547  0.867901  0.994996

[334 rows x 5 columns]

In [28]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.994996  0.867901  0.273547  0.511122     groot
1    0.739970  0.805434  0.458345  0.982297  0.953755
2    0.937870  0.714775  0.752267  0.637125  0.828743
3    0.470067  0.305622  0.214938  0.300200  0.682883
4    0.787123  0.649134  0.921691  0.996165   0.09502
..        ...       ...       ...       ...       ...
329  0.456191  0.520564  0.792386  0.396553  0.768136
330  0.291497  0.136945  0.276145  0.730970  0.605076
331  0.596985  0.839148  0.633201  0.709938  0.444179
332  0.518201  0.994679  0.501760  0.468766  0.772452
333  0.645354  0.782151  0.107543  0.530838  0.200233

[334 rows x 5 columns]

In [29]:
newdf[0]

0         groot
1      0.953755
2      0.828743
3      0.682883
4       0.09502
         ...
329    0.768136
330    0.605076
331    0.444179
332    0.772452
333    0.200233
Name: 0, Length: 334, dtype: object

In [30]:
type(newdf[0])

pandas.Series

In [31]:
newdf2=newdf.copy()

In [32]:
newdf.loc[0,0] = 95

In [33]:
newdf

            0         1         2         3         4
0          95  0.511122  0.273547  0.867901  0.994996
1    0.953755  0.982297  0.458345  0.805434  0.739970
2    0.828743  0.637125  0.752267  0.714775  0.937870
3    0.682883  0.300200  0.214938  0.305622  0.470067
4     0.09502  0.996165  0.921691  0.649134  0.787123
..        ...       ...       ...       ...       ...
329  0.768136  0.396553  0.792386  0.520564  0.456191
330  0.605076  0.730970  0.276145  0.136945  0.291497
331  0.444179  0.709938  0.633201  0.839148  0.596985
332  0.772452  0.468766  0.501760  0.994679  0.518201
333  0.200233  0.530838  0.107543  0.782151  0.645354

[334 rows x 5 columns]

In [34]:
newdf.loc[0,0]=980
newdf.head(7)

          0         1         2         3         4
0       980  0.511122  0.273547  0.867901  0.994996
1  0.953755  0.982297  0.458345  0.805434  0.739970
2  0.828743  0.637125  0.752267  0.714775  0.937870
3  0.682883  0.300200  0.214938  0.305622  0.470067
4   0.09502  0.996165  0.921691  0.649134  0.787123
5  0.799055  0.606201  0.624845  0.259708  0.627978
6  0.288879  0.853872  0.945271  0.273697  0.501682

In [35]:
newdf.columns=list("ABCDE")
newdf

            A         B         C         D         E
0         980  0.511122  0.273547  0.867901  0.994996
1    0.953755  0.982297  0.458345  0.805434  0.739970
2    0.828743  0.637125  0.752267  0.714775  0.937870
3    0.682883  0.300200  0.214938  0.305622  0.470067
4     0.09502  0.996165  0.921691  0.649134  0.787123
..        ...       ...       ...       ...       ...
329  0.768136  0.396553  0.792386  0.520564  0.456191
330  0.605076  0.730970  0.276145  0.136945  0.291497
331  0.444179  0.709938  0.633201  0.839148  0.596985
332  0.772452  0.468766  0.501760  0.994679  0.518201
333  0.200233  0.530838  0.107543  0.782151  0.645354

[334 rows x 5 columns]

In [36]:
newdf.loc[0,0]=990

In [37]:
newdf.head()

          A         B         C         D         E      0
0       980  0.511122  0.273547  0.867901  0.994996  990.0
1  0.953755  0.982297  0.458345  0.805434  0.739970    NaN
2  0.828743  0.637125  0.752267  0.714775  0.937870    NaN
3  0.682883  0.300200  0.214938  0.305622  0.470067    NaN
4   0.09502  0.996165  0.921691  0.649134  0.787123    NaN

In [38]:
newdf = newdf.drop(0, axis=1)
newdf.head()

          A         B         C         D         E
0       980  0.511122  0.273547  0.867901  0.994996
1  0.953755  0.982297  0.458345  0.805434  0.739970
2  0.828743  0.637125  0.752267  0.714775  0.937870
3  0.682883  0.300200  0.214938  0.305622  0.470067
4   0.09502  0.996165  0.921691  0.649134  0.787123

In [39]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.458345  0.805434
2  0.752267  0.714775

In [40]:
newdf.loc[:,['C','D']]

            C         D
0    0.273547  0.867901
1    0.458345  0.805434
2    0.752267  0.714775
3    0.214938  0.305622
4    0.921691  0.649134
..        ...       ...
329  0.792386  0.520564
330  0.276145  0.136945
331  0.633201  0.839148
332  0.501760  0.994679
333  0.107543  0.782151

[334 rows x 2 columns]

In [41]:
newdf.loc[[1,2],:]

          A         B         C         D        E
1  0.953755  0.982297  0.458345  0.805434  0.73997
2  0.828743  0.637125  0.752267  0.714775  0.93787

In [42]:
newdf.loc[(newdf['A']<0.3)&(newdf['C']>0.1)]

            A         B         C         D         E
4     0.09502  0.996165  0.921691  0.649134  0.787123
6    0.288879  0.853872  0.945271  0.273697  0.501682
8    0.297316  0.414484  0.535699  0.342217  0.310022
11   0.024738  0.906879  0.652596  0.304202  0.672936
15    0.03892  0.584078  0.952310  0.495112  0.522559
..        ...       ...       ...       ...       ...
314  0.274921  0.889767  0.462041  0.229088  0.796568
315  0.203994  0.783733  0.779042  0.347636  0.095318
319  0.253393  0.991738  0.561723  0.623658  0.800361
323  0.291237  0.193122  0.291739  0.190795  0.591921
333  0.200233  0.530838  0.107543  0.782151  0.645354

[85 rows x 5 columns]

In [43]:
newdf.iloc[0,4]

np.float64(0.9949956102916867)

In [44]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.511122  0.273547
1  0.982297  0.458345

In [45]:
newdf.head(3)

          A         B         C         D         E
0       980  0.511122  0.273547  0.867901  0.994996
1  0.953755  0.982297  0.458345  0.805434  0.739970
2  0.828743  0.637125  0.752267  0.714775  0.937870

In [46]:
newdf.drop([0])

            A         B         C         D         E
1    0.953755  0.982297  0.458345  0.805434  0.739970
2    0.828743  0.637125  0.752267  0.714775  0.937870
3    0.682883  0.300200  0.214938  0.305622  0.470067
4     0.09502  0.996165  0.921691  0.649134  0.787123
5    0.799055  0.606201  0.624845  0.259708  0.627978
..        ...       ...       ...       ...       ...
329  0.768136  0.396553  0.792386  0.520564  0.456191
330  0.605076  0.730970  0.276145  0.136945  0.291497
331  0.444179  0.709938  0.633201  0.839148  0.596985
332  0.772452  0.468766  0.501760  0.994679  0.518201
333  0.200233  0.530838  0.107543  0.782151  0.645354

[333 rows x 5 columns]

In [47]:
newdf.drop(['A','C'],axis=1)

            B         D         E
0    0.511122  0.867901  0.994996
1    0.982297  0.805434  0.739970
2    0.637125  0.714775  0.937870
3    0.300200  0.305622  0.470067
4    0.996165  0.649134  0.787123
..        ...       ...       ...
329  0.396553  0.520564  0.456191
330  0.730970  0.136945  0.291497
331  0.709938  0.839148  0.596985
332  0.468766  0.994679  0.518201
333  0.530838  0.782151  0.645354

[334 rows x 3 columns]

In [48]:
newdf.drop(['D','E'],axis=1, inplace=True)

In [49]:
newdf

            A         B         C
0         980  0.511122  0.273547
1    0.953755  0.982297  0.458345
2    0.828743  0.637125  0.752267
3    0.682883  0.300200  0.214938
4     0.09502  0.996165  0.921691
..        ...       ...       ...
329  0.768136  0.396553  0.792386
330  0.605076  0.730970  0.276145
331  0.444179  0.709938  0.633201
332  0.772452  0.468766  0.501760
333  0.200233  0.530838  0.107543

[334 rows x 3 columns]

In [50]:
newdf.reset_index(drop=True, inplace=True)
newdf.head(3)

          A         B         C
0       980  0.511122  0.273547
1  0.953755  0.982297  0.458345
2  0.828743  0.637125  0.752267

In [51]:
newdf['B']=None

In [52]:
newdf

            A     B         C
0         980  None  0.273547
1    0.953755  None  0.458345
2    0.828743  None  0.752267
3    0.682883  None  0.214938
4     0.09502  None  0.921691
..        ...   ...       ...
329  0.768136  None  0.792386
330  0.605076  None  0.276145
331  0.444179  None  0.633201
332  0.772452  None  0.501760
333  0.200233  None  0.107543

[334 rows x 3 columns]

In [53]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
329    True
330    True
331    True
332    True
333    True
Name: B, Length: 334, dtype: bool

In [54]:
newdf.loc[:,['B']]=90
newdf

            A   B         C
0         980  90  0.273547
1    0.953755  90  0.458345
2    0.828743  90  0.752267
3    0.682883  90  0.214938
4     0.09502  90  0.921691
..        ...  ..       ...
329  0.768136  90  0.792386
330  0.605076  90  0.276145
331  0.444179  90  0.633201
332  0.772452  90  0.501760
333  0.200233  90  0.107543

[334 rows x 3 columns]

In [55]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       334 non-null    object
 1   B       334 non-null    object
 2   C       334 non-null    float64
dtypes: float64(1), object(2)
memory usage: 8.0+ KB

In [56]:
newdf.notnull()

        A     B     C
0    True  True  True
1    True  True  True
2    True  True  True
3    True  True  True
4    True  True  True
..    ...   ...   ...
329  True  True  True
330  True  True  True
331  True  True  True
332  True  True  True
333  True  True  True

[334 rows x 3 columns]

In [65]:
data=pd.read_excel('F20file4.xlsx',sheet_name='Sheet2')
data

  Unnamed: 0   name  generations Country
0      first   F-22            5     USA
1     second  SU-57            5  Russia
2      third   J-20            5   China
3     fourth   F-18            4     USA