# PANDAS

In [280]:
import numpy as np 
import pandas as pd

In [281]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [282]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [283]:
df.to_csv('F20file1.csv')

In [284]:
df.to_csv('F20file2.csv',index=False)

In [285]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [286]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [287]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [288]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [289]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [290]:
z['name'][0]

'F-22'

In [291]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [292]:
#z.to_csv('F20file3.csv')

In [293]:
ser=pd.Series(np.random.rand(10))
ser

0    0.890220
1    0.322967
2    0.267874
3    0.706187
4    0.590908
5    0.427016
6    0.584151
7    0.336139
8    0.633717
9    0.560859
dtype: float64

In [294]:
type(ser)

pandas.Series

In [295]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.619675  0.995665  0.054509  0.041357  0.738315
1  0.486550  0.967750  0.814463  0.736404  0.425403
2  0.496651  0.613020  0.792711  0.344241  0.412510
3  0.547142  0.115953  0.692183  0.958755  0.953727
4  0.072936  0.483013  0.486602  0.060181  0.753301

In [296]:
type(newdf)

pandas.DataFrame

In [297]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.491661    0.499258    0.513515    0.482825    0.532282
std      0.294600    0.278638    0.293051    0.294861    0.278040
min      0.009804    0.000183    0.001007    0.001910    0.001390
25%      0.219095    0.286298    0.241952    0.226458    0.296410
50%      0.489205    0.487197    0.548024    0.457415    0.549174
75%      0.749633    0.737644    0.750457    0.737329    0.761999
max      0.999847    0.995665    0.996836    0.998252    0.996938

In [298]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [299]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [300]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [301]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [302]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [303]:
newdf.to_numpy()

array([['groot', 0.9956648632687373, 0.054509279807836486,
        0.0413569004879375, 0.7383153335194341],
       [0.48654981220826854, 0.9677501206037156, 0.8144626568926635,
        0.7364044440554117, 0.4254030798599209],
       [0.49665088781528366, 0.6130201276769865, 0.7927107676420783,
        0.3442411371929367, 0.4125100259649944],
       ...,
       [0.06173882007391007, 0.8609132438971285, 0.7205314157756424,
        0.9576116416659791, 0.21749293755969734],
       [0.5229512019833376, 0.8327860497277595, 0.48672516403411303,
        0.19132398076033708, 0.44505995766479645],
       [0.9381545692188029, 0.7345892009753764, 0.4440385501517501,
        0.8714377963878451, 0.7153472929401558]],
      shape=(334, 5), dtype=object)

In [304]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.48655,0.496651,0.547142,0.072936,0.328298,0.620213,0.815576,0.194616,0.535194,...,0.100111,0.722065,0.111344,0.157685,0.173257,0.317191,0.879776,0.061739,0.522951,0.938155
1,0.995665,0.96775,0.61302,0.115953,0.483013,0.924006,0.718081,0.515947,0.090351,0.191862,...,0.741992,0.925506,0.215289,0.435774,0.355701,0.781878,0.295963,0.860913,0.832786,0.734589
2,0.054509,0.814463,0.792711,0.692183,0.486602,0.850024,0.653541,0.752462,0.143229,0.433694,...,0.192836,0.945209,0.348616,0.249014,0.006537,0.657341,0.228797,0.720531,0.486725,0.444039
3,0.041357,0.736404,0.344241,0.958755,0.060181,0.697899,0.439245,0.750923,0.33728,0.748712,...,0.27171,0.310703,0.584802,0.042478,0.159559,0.623512,0.794482,0.957612,0.191324,0.871438
4,0.738315,0.425403,0.41251,0.953727,0.753301,0.926019,0.654271,0.301778,0.135768,0.652067,...,0.705055,0.867887,0.473904,0.602196,0.766318,0.985397,0.794375,0.217493,0.44506,0.715347

In [305]:
newdf.head()

          0         1         2         3         4
0     groot  0.995665  0.054509  0.041357  0.738315
1   0.48655  0.967750  0.814463  0.736404  0.425403
2  0.496651  0.613020  0.792711  0.344241  0.412510
3  0.547142  0.115953  0.692183  0.958755  0.953727
4  0.072936  0.483013  0.486602  0.060181  0.753301

In [306]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.938155  0.734589  0.444039  0.871438  0.715347
332  0.522951  0.832786  0.486725  0.191324  0.445060
331  0.061739  0.860913  0.720531  0.957612  0.217493
330  0.879776  0.295963  0.228797  0.794482  0.794375
329  0.317191  0.781878  0.657341  0.623512  0.985397
..        ...       ...       ...       ...       ...
4    0.072936  0.483013  0.486602  0.060181  0.753301
3    0.547142  0.115953  0.692183  0.958755  0.953727
2    0.496651  0.613020  0.792711  0.344241  0.412510
1     0.48655  0.967750  0.814463  0.736404  0.425403
0       groot  0.995665  0.054509  0.041357  0.738315

[334 rows x 5 columns]

In [307]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.738315  0.041357  0.054509  0.995665     groot
1    0.425403  0.736404  0.814463  0.967750   0.48655
2    0.412510  0.344241  0.792711  0.613020  0.496651
3    0.953727  0.958755  0.692183  0.115953  0.547142
4    0.753301  0.060181  0.486602  0.483013  0.072936
..        ...       ...       ...       ...       ...
329  0.985397  0.623512  0.657341  0.781878  0.317191
330  0.794375  0.794482  0.228797  0.295963  0.879776
331  0.217493  0.957612  0.720531  0.860913  0.061739
332  0.445060  0.191324  0.486725  0.832786  0.522951
333  0.715347  0.871438  0.444039  0.734589  0.938155

[334 rows x 5 columns]

In [308]:
newdf[0]

0         groot
1       0.48655
2      0.496651
3      0.547142
4      0.072936
         ...
329    0.317191
330    0.879776
331    0.061739
332    0.522951
333    0.938155
Name: 0, Length: 334, dtype: object

In [309]:
type(newdf[0])

pandas.Series

In [325]:
newdf2=newdf.copy()

In [323]:
newdf.loc[0,0] = 95

In [324]:
newdf

            0         1         2         3         4
0          95  0.995665  0.054509  0.041357  0.738315
1     0.48655  0.967750  0.814463  0.736404  0.425403
2    0.496651  0.613020  0.792711  0.344241  0.412510
3    0.547142  0.115953  0.692183  0.958755  0.953727
4    0.072936  0.483013  0.486602  0.060181  0.753301
..        ...       ...       ...       ...       ...
329  0.317191  0.781878  0.657341  0.623512  0.985397
330  0.879776  0.295963  0.228797  0.794482  0.794375
331  0.061739  0.860913  0.720531  0.957612  0.217493
332  0.522951  0.832786  0.486725  0.191324  0.445060
333  0.938155  0.734589  0.444039  0.871438  0.715347

[334 rows x 5 columns]

In [326]:
newdf.loc[0,0]=980
newdf.head(7)

          0         1         2         3         4
0       980  0.995665  0.054509  0.041357  0.738315
1   0.48655  0.967750  0.814463  0.736404  0.425403
2  0.496651  0.613020  0.792711  0.344241  0.412510
3  0.547142  0.115953  0.692183  0.958755  0.953727
4  0.072936  0.483013  0.486602  0.060181  0.753301
5  0.328298  0.924006  0.850024  0.697899  0.926019
6  0.620213  0.718081  0.653541  0.439245  0.654271

In [327]:
newdf.columns=list("ABCDE")
newdf

            A         B         C         D         E
0         980  0.995665  0.054509  0.041357  0.738315
1     0.48655  0.967750  0.814463  0.736404  0.425403
2    0.496651  0.613020  0.792711  0.344241  0.412510
3    0.547142  0.115953  0.692183  0.958755  0.953727
4    0.072936  0.483013  0.486602  0.060181  0.753301
..        ...       ...       ...       ...       ...
329  0.317191  0.781878  0.657341  0.623512  0.985397
330  0.879776  0.295963  0.228797  0.794482  0.794375
331  0.061739  0.860913  0.720531  0.957612  0.217493
332  0.522951  0.832786  0.486725  0.191324  0.445060
333  0.938155  0.734589  0.444039  0.871438  0.715347

[334 rows x 5 columns]

In [ ]:
newdf.drop(E')