# PANDAS

In [6]:
import numpy as np 
import pandas as pd

In [7]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [8]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [9]:
df.to_csv('F20file1.csv')

In [10]:
df.to_csv('F20file2.csv',index=False)

In [11]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [12]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [13]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [14]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [15]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [16]:
z['name'][0]

'F-22'

In [17]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [18]:
#z.to_csv('F20file3.csv')

In [19]:
ser=pd.Series(np.random.rand(10))
ser

0    0.291507
1    0.727089
2    0.458826
3    0.462722
4    0.293379
5    0.635915
6    0.616536
7    0.022134
8    0.388762
9    0.613672
dtype: float64

In [20]:
type(ser)

pandas.Series

In [21]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.830240  0.735996  0.215665  0.790229  0.507306
1  0.248281  0.073281  0.835875  0.859912  0.237492
2  0.319878  0.933109  0.474494  0.630229  0.577425
3  0.843849  0.018990  0.539709  0.861263  0.941160
4  0.171850  0.143008  0.313974  0.144470  0.177460

In [22]:
type(newdf)

pandas.DataFrame

In [23]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.512985    0.493107    0.498129    0.491651    0.510963
std      0.288554    0.282194    0.280589    0.291529    0.286868
min      0.000706    0.000916    0.005701    0.004203    0.003006
25%      0.271523    0.255775    0.266275    0.229246    0.282250
50%      0.487226    0.480700    0.493467    0.493394    0.521577
75%      0.758405    0.726296    0.726874    0.740742    0.763939
max      0.991565    0.994398    0.999668    0.999448    0.990803

In [24]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [25]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [26]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [27]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [28]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [29]:
newdf.to_numpy()

array([['groot', 0.7359964382324711, 0.21566522788437748,
        0.790229058279127, 0.5073059043349232],
       [0.24828133457429602, 0.07328120069350641, 0.8358750959623215,
        0.8599116277505339, 0.23749178627712775],
       [0.3198781783698086, 0.9331093653346523, 0.47449378965463007,
        0.630229328498897, 0.5774248525362131],
       ...,
       [0.6647807114712827, 0.6581876575960338, 0.3853277021538204,
        0.6024308989162309, 0.8044622376311492],
       [0.3771733008722138, 0.41825051609926167, 0.9486534170129715,
        0.17762960281349383, 0.018030502106443524],
       [0.3951839192454669, 0.531651832162914, 0.21676377222802745,
        0.39092748953012246, 0.8760607022044378]],
      shape=(334, 5), dtype=object)

In [30]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.248281,0.319878,0.843849,0.17185,0.483169,0.484637,0.222346,0.758445,0.273839,...,0.156728,0.440874,0.294875,0.77348,0.002099,0.751421,0.977564,0.664781,0.377173,0.395184
1,0.735996,0.073281,0.933109,0.01899,0.143008,0.529296,0.130512,0.666242,0.380052,0.73756,...,0.788715,0.430417,0.470233,0.769214,0.188804,0.339067,0.737564,0.658188,0.418251,0.531652
2,0.215665,0.835875,0.474494,0.539709,0.313974,0.586315,0.042543,0.886693,0.859346,0.770762,...,0.292957,0.573618,0.347462,0.980571,0.471009,0.8471,0.115436,0.385328,0.948653,0.216764
3,0.790229,0.859912,0.630229,0.861263,0.14447,0.516963,0.227656,0.305539,0.465902,0.486327,...,0.032615,0.210279,0.331514,0.24425,0.781798,0.615042,0.592602,0.602431,0.17763,0.390927
4,0.507306,0.237492,0.577425,0.94116,0.17746,0.886898,0.382673,0.556356,0.90737,0.111011,...,0.532718,0.080906,0.260465,0.722644,0.070794,0.858257,0.70091,0.804462,0.018031,0.876061

In [31]:
newdf.head()

          0         1         2         3         4
0     groot  0.735996  0.215665  0.790229  0.507306
1  0.248281  0.073281  0.835875  0.859912  0.237492
2  0.319878  0.933109  0.474494  0.630229  0.577425
3  0.843849  0.018990  0.539709  0.861263  0.941160
4   0.17185  0.143008  0.313974  0.144470  0.177460

In [32]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.395184  0.531652  0.216764  0.390927  0.876061
332  0.377173  0.418251  0.948653  0.177630  0.018031
331  0.664781  0.658188  0.385328  0.602431  0.804462
330  0.977564  0.737564  0.115436  0.592602  0.700910
329  0.751421  0.339067  0.847100  0.615042  0.858257
..        ...       ...       ...       ...       ...
4     0.17185  0.143008  0.313974  0.144470  0.177460
3    0.843849  0.018990  0.539709  0.861263  0.941160
2    0.319878  0.933109  0.474494  0.630229  0.577425
1    0.248281  0.073281  0.835875  0.859912  0.237492
0       groot  0.735996  0.215665  0.790229  0.507306

[334 rows x 5 columns]

In [33]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.507306  0.790229  0.215665  0.735996     groot
1    0.237492  0.859912  0.835875  0.073281  0.248281
2    0.577425  0.630229  0.474494  0.933109  0.319878
3    0.941160  0.861263  0.539709  0.018990  0.843849
4    0.177460  0.144470  0.313974  0.143008   0.17185
..        ...       ...       ...       ...       ...
329  0.858257  0.615042  0.847100  0.339067  0.751421
330  0.700910  0.592602  0.115436  0.737564  0.977564
331  0.804462  0.602431  0.385328  0.658188  0.664781
332  0.018031  0.177630  0.948653  0.418251  0.377173
333  0.876061  0.390927  0.216764  0.531652  0.395184

[334 rows x 5 columns]

In [34]:
newdf[0]

0         groot
1      0.248281
2      0.319878
3      0.843849
4       0.17185
         ...
329    0.751421
330    0.977564
331    0.664781
332    0.377173
333    0.395184
Name: 0, Length: 334, dtype: object

In [35]:
type(newdf[0])

pandas.Series

In [36]:
newdf2=newdf.copy()

In [37]:
newdf.loc[0,0] = 95

In [38]:
newdf

            0         1         2         3         4
0          95  0.735996  0.215665  0.790229  0.507306
1    0.248281  0.073281  0.835875  0.859912  0.237492
2    0.319878  0.933109  0.474494  0.630229  0.577425
3    0.843849  0.018990  0.539709  0.861263  0.941160
4     0.17185  0.143008  0.313974  0.144470  0.177460
..        ...       ...       ...       ...       ...
329  0.751421  0.339067  0.847100  0.615042  0.858257
330  0.977564  0.737564  0.115436  0.592602  0.700910
331  0.664781  0.658188  0.385328  0.602431  0.804462
332  0.377173  0.418251  0.948653  0.177630  0.018031
333  0.395184  0.531652  0.216764  0.390927  0.876061

[334 rows x 5 columns]

In [39]:
newdf.loc[0,0]=980
newdf.head(7)

          0         1         2         3         4
0       980  0.735996  0.215665  0.790229  0.507306
1  0.248281  0.073281  0.835875  0.859912  0.237492
2  0.319878  0.933109  0.474494  0.630229  0.577425
3  0.843849  0.018990  0.539709  0.861263  0.941160
4   0.17185  0.143008  0.313974  0.144470  0.177460
5  0.483169  0.529296  0.586315  0.516963  0.886898
6  0.484637  0.130512  0.042543  0.227656  0.382673

In [40]:
newdf.columns=list("ABCDE")
newdf

            A         B         C         D         E
0         980  0.735996  0.215665  0.790229  0.507306
1    0.248281  0.073281  0.835875  0.859912  0.237492
2    0.319878  0.933109  0.474494  0.630229  0.577425
3    0.843849  0.018990  0.539709  0.861263  0.941160
4     0.17185  0.143008  0.313974  0.144470  0.177460
..        ...       ...       ...       ...       ...
329  0.751421  0.339067  0.847100  0.615042  0.858257
330  0.977564  0.737564  0.115436  0.592602  0.700910
331  0.664781  0.658188  0.385328  0.602431  0.804462
332  0.377173  0.418251  0.948653  0.177630  0.018031
333  0.395184  0.531652  0.216764  0.390927  0.876061

[334 rows x 5 columns]

In [41]:
newdf.loc[0,0]=990

In [42]:
newdf.head()

          A         B         C         D         E      0
0       980  0.735996  0.215665  0.790229  0.507306  990.0
1  0.248281  0.073281  0.835875  0.859912  0.237492    NaN
2  0.319878  0.933109  0.474494  0.630229  0.577425    NaN
3  0.843849  0.018990  0.539709  0.861263  0.941160    NaN
4   0.17185  0.143008  0.313974  0.144470  0.177460    NaN

In [43]:
newdf = newdf.drop(0, axis=1)
newdf.head()

          A         B         C         D         E
0       980  0.735996  0.215665  0.790229  0.507306
1  0.248281  0.073281  0.835875  0.859912  0.237492
2  0.319878  0.933109  0.474494  0.630229  0.577425
3  0.843849  0.018990  0.539709  0.861263  0.941160
4   0.17185  0.143008  0.313974  0.144470  0.177460

In [45]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.835875  0.859912
2  0.474494  0.630229

In [46]:
newdf.loc[:,['C','D']]

            C         D
0    0.215665  0.790229
1    0.835875  0.859912
2    0.474494  0.630229
3    0.539709  0.861263
4    0.313974  0.144470
..        ...       ...
329  0.847100  0.615042
330  0.115436  0.592602
331  0.385328  0.602431
332  0.948653  0.177630
333  0.216764  0.390927

[334 rows x 2 columns]

In [47]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.248281  0.073281  0.835875  0.859912  0.237492
2  0.319878  0.933109  0.474494  0.630229  0.577425

In [50]:
newdf.loc[(newdf['A']<0.3)&(newdf['C']>0.1)]

            A         B         C         D         E
1    0.248281  0.073281  0.835875  0.859912  0.237492
4     0.17185  0.143008  0.313974  0.144470  0.177460
7    0.222346  0.666242  0.886693  0.305539  0.556356
9    0.273839  0.737560  0.770762  0.486327  0.111011
10   0.000706  0.590899  0.500170  0.253367  0.043836
..        ...       ...       ...       ...       ...
308  0.180642  0.483946  0.364370  0.290185  0.990803
320   0.13551  0.368681  0.290298  0.829395  0.074148
324  0.156728  0.788715  0.292957  0.032615  0.532718
326  0.294875  0.470233  0.347462  0.331514  0.260465
328  0.002099  0.188804  0.471009  0.781798  0.070794

[86 rows x 5 columns]

In [51]:
newdf.iloc[0,4]

np.float64(0.5073059043349232)

In [52]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.735996  0.215665
1  0.073281  0.835875

In [53]:
newdf.head(3)

          A         B         C         D         E
0       980  0.735996  0.215665  0.790229  0.507306
1  0.248281  0.073281  0.835875  0.859912  0.237492
2  0.319878  0.933109  0.474494  0.630229  0.577425

In [59]:
newdf.drop([0])

            B         D         E
1    0.073281  0.859912  0.237492
2    0.933109  0.630229  0.577425
3    0.018990  0.861263  0.941160
4    0.143008  0.144470  0.177460
5    0.529296  0.516963  0.886898
..        ...       ...       ...
329  0.339067  0.615042  0.858257
330  0.737564  0.592602  0.700910
331  0.658188  0.602431  0.804462
332  0.418251  0.177630  0.018031
333  0.531652  0.390927  0.876061

[333 rows x 3 columns]

In [55]:
newdf.drop(['A','C'],axis=1)

            B         D         E
0    0.735996  0.790229  0.507306
1    0.073281  0.859912  0.237492
2    0.933109  0.630229  0.577425
3    0.018990  0.861263  0.941160
4    0.143008  0.144470  0.177460
..        ...       ...       ...
329  0.339067  0.615042  0.858257
330  0.737564  0.592602  0.700910
331  0.658188  0.602431  0.804462
332  0.418251  0.177630  0.018031
333  0.531652  0.390927  0.876061

[334 rows x 3 columns]

In [ ]:
newdf.drop(['D','E'],axis=1, inplace=True)

KeyError: "['D', 'E'] not found in axis"