# PANDAS

In [22]:
import numpy as np 
import pandas as pd

In [23]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [24]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [25]:
df.to_csv('F20file1.csv')

In [26]:
df.to_csv('F20file2.csv',index=False)

In [27]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [28]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [29]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [30]:
z=pd.read_csv('F20file3.csv')
z

    name generations Country
0   F-22         5th     USA
1  SU-57         5th  Russia
2   J-20         5th   China
3   F-35         5th     USA

In [31]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [32]:
z['name'][0]

'F-22'

In [33]:
z.index=['first','second','third','fourth']
z

         name generations Country
first    F-22         5th     USA
second  SU-57         5th  Russia
third    J-20         5th   China
fourth   F-35         5th     USA

In [36]:
z.to_csv('F20file3.csv')

In [37]:
ser=pd.Series(np.random.rand(10))
ser

0    0.349345
1    0.448532
2    0.436258
3    0.479489
4    0.636410
5    0.351227
6    0.908611
7    0.019150
8    0.087708
9    0.431888
dtype: float64