# PANDAS

In [14]:
import numpy as np 
import pandas as pd

In [2]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [3]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [4]:
df.to_csv('F20file1.csv')

In [5]:
df.to_csv('F20file2.csv',index=False)

In [6]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [7]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [8]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [9]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [10]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [11]:
z['name'][0]

'F-22'

In [12]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [16]:
#z.to_csv('F20file3.csv')

In [ ]:
ser=pd.Series(np.random.rand(10))
ser

0    0.622722
1    0.199052
2    0.256186
3    0.824833
4    0.174820
5    0.565593
6    0.974885
7    0.873063
8    0.668318
9    0.630536
dtype: float64

In [ ]:
type(ser)

pandas.Series

In [17]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.397314  0.395114  0.059438  0.890089  0.421118
1  0.297441  0.475851  0.969424  0.224565  0.209864
2  0.138517  0.118858  0.285406  0.858676  0.528066
3  0.354476  0.956019  0.392527  0.347017  0.466866
4  0.671708  0.069636  0.936762  0.167340  0.878884

In [18]:
type(newdf)

pandas.DataFrame

In [20]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.501776    0.505082    0.466923    0.495171    0.531809
std      0.280268    0.312803    0.282638    0.286338    0.305669
min      0.002231    0.002412    0.002967    0.010566    0.003013
25%      0.262915    0.209948    0.221242    0.254612    0.256360
50%      0.514602    0.524307    0.463532    0.483870    0.563363
75%      0.743004    0.780334    0.722333    0.737822    0.805070
max      0.999637    0.999675    0.996215    0.998312    0.999642

In [21]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [27]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [28]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [29]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [30]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [32]:
newdf.to_numpy()

array([['groot', 0.3951136760139796, 0.05943847179504225,
        0.8900888210847184, 0.4211182238389467],
       [0.2974410751639046, 0.47585054816215366, 0.969424148544849,
        0.22456545708488285, 0.209864210035128],
       [0.13851663918358847, 0.11885798936609326, 0.28540607530366535,
        0.8586759023852618, 0.5280661358798343],
       ...,
       [0.7703501907534059, 0.7219056197572247, 0.3445322791247205,
        0.11761270706130789, 0.6755873299537606],
       [0.7014518014768408, 0.4939573240970001, 0.5124474251781476,
        0.473155549744428, 0.3499583000099299],
       [0.6435268972538496, 0.9398584501005003, 0.521760710117404,
        0.2040842817260291, 0.5988867023396726]],
      shape=(334, 5), dtype=object)

In [33]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.297441,0.138517,0.354476,0.671708,0.671298,0.23278,0.79822,0.585297,0.171768,...,0.178295,0.290215,0.507978,0.712279,0.878363,0.743618,0.786512,0.77035,0.701452,0.643527
1,0.395114,0.475851,0.118858,0.956019,0.069636,0.476753,0.883933,0.11869,0.130959,0.929809,...,0.614713,0.460829,0.114363,0.849405,0.226476,0.951893,0.896134,0.721906,0.493957,0.939858
2,0.059438,0.969424,0.285406,0.392527,0.936762,0.915771,0.601197,0.533435,0.081022,0.596758,...,0.230154,0.738092,0.763449,0.193639,0.590431,0.370981,0.653899,0.344532,0.512447,0.521761
3,0.890089,0.224565,0.858676,0.347017,0.16734,0.306886,0.158182,0.793633,0.980179,0.774153,...,0.086048,0.775343,0.555481,0.263456,0.755718,0.749625,0.648385,0.117613,0.473156,0.204084
4,0.421118,0.209864,0.528066,0.466866,0.878884,0.174975,0.077582,0.777527,0.211624,0.845496,...,0.064649,0.877514,0.932771,0.078921,0.719603,0.140535,0.552851,0.675587,0.349958,0.598887

In [34]:
newdf.head()

          0         1         2         3         4
0     groot  0.395114  0.059438  0.890089  0.421118
1  0.297441  0.475851  0.969424  0.224565  0.209864
2  0.138517  0.118858  0.285406  0.858676  0.528066
3  0.354476  0.956019  0.392527  0.347017  0.466866
4  0.671708  0.069636  0.936762  0.167340  0.878884

In [35]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.643527  0.939858  0.521761  0.204084  0.598887
332  0.701452  0.493957  0.512447  0.473156  0.349958
331   0.77035  0.721906  0.344532  0.117613  0.675587
330  0.786512  0.896134  0.653899  0.648385  0.552851
329  0.743618  0.951893  0.370981  0.749625  0.140535
..        ...       ...       ...       ...       ...
4    0.671708  0.069636  0.936762  0.167340  0.878884
3    0.354476  0.956019  0.392527  0.347017  0.466866
2    0.138517  0.118858  0.285406  0.858676  0.528066
1    0.297441  0.475851  0.969424  0.224565  0.209864
0       groot  0.395114  0.059438  0.890089  0.421118

[334 rows x 5 columns]

In [36]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.421118  0.890089  0.059438  0.395114     groot
1    0.209864  0.224565  0.969424  0.475851  0.297441
2    0.528066  0.858676  0.285406  0.118858  0.138517
3    0.466866  0.347017  0.392527  0.956019  0.354476
4    0.878884  0.167340  0.936762  0.069636  0.671708
..        ...       ...       ...       ...       ...
329  0.140535  0.749625  0.370981  0.951893  0.743618
330  0.552851  0.648385  0.653899  0.896134  0.786512
331  0.675587  0.117613  0.344532  0.721906   0.77035
332  0.349958  0.473156  0.512447  0.493957  0.701452
333  0.598887  0.204084  0.521761  0.939858  0.643527

[334 rows x 5 columns]

In [37]:
newdf[0]

0         groot
1      0.297441
2      0.138517
3      0.354476
4      0.671708
         ...
329    0.743618
330    0.786512
331     0.77035
332    0.701452
333    0.643527
Name: 0, Length: 334, dtype: object

In [38]:
type(newdf[0])

pandas.Series

In [55]:
newdf2=newdf.copy()

In [61]:
# newdf[0] = newdf[0].astype(object)
# newdf.loc[0, 0] = 95

In [60]:
newdf

            0         1         2         3         4
0          95  0.395114  0.059438  0.890089  0.421118
1    0.297441  0.475851  0.969424  0.224565  0.209864
2    0.138517  0.118858  0.285406  0.858676  0.528066
3    0.354476  0.956019  0.392527  0.347017  0.466866
4    0.671708  0.069636  0.936762  0.167340  0.878884
..        ...       ...       ...       ...       ...
329  0.743618  0.951893  0.370981  0.749625  0.140535
330  0.786512  0.896134  0.653899  0.648385  0.552851
331   0.77035  0.721906  0.344532  0.117613  0.675587
332  0.701452  0.493957  0.512447  0.473156  0.349958
333  0.643527  0.939858  0.521761  0.204084  0.598887

[334 rows x 5 columns]