# PANDAS

In [168]:
import numpy as np 
import pandas as pd

In [169]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [170]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [171]:
df.to_csv('F20file1.csv')

In [172]:
df.to_csv('F20file2.csv',index=False)

In [173]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [174]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [175]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [176]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [177]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [178]:
z['name'][0]

'F-22'

In [179]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [180]:
#z.to_csv('F20file3.csv')

In [181]:
ser=pd.Series(np.random.rand(10))
ser

0    0.242064
1    0.795374
2    0.783655
3    0.929930
4    0.099244
5    0.368670
6    0.120904
7    0.774732
8    0.943949
9    0.145104
dtype: float64

In [182]:
type(ser)

pandas.Series

In [183]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.550203  0.760962  0.813566  0.710205  0.566004
1  0.217226  0.944573  0.753998  0.552001  0.182937
2  0.599351  0.170901  0.068810  0.056614  0.406402
3  0.125551  0.004809  0.281470  0.678613  0.159748
4  0.550419  0.627881  0.553374  0.510162  0.529592

In [184]:
type(newdf)

pandas.DataFrame

In [185]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.477929    0.488885    0.527899    0.495330    0.486082
std      0.287707    0.282155    0.279196    0.283415    0.277862
min      0.003041    0.004456    0.001670    0.003374    0.001211
25%      0.217276    0.253705    0.316816    0.268149    0.242754
50%      0.468956    0.465505    0.540207    0.469296    0.487396
75%      0.711407    0.725960    0.763569    0.730974    0.714315
max      0.998348    0.997781    0.999862    0.999711    0.999912

In [186]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [187]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [188]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [189]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [190]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [191]:
newdf.to_numpy()

array([['groot', 0.760961757656923, 0.8135662937865641,
        0.7102050148890694, 0.5660036854801535],
       [0.21722612769545369, 0.9445725043444086, 0.7539982408179584,
        0.5520012436336416, 0.1829370222731148],
       [0.5993508822442751, 0.17090055704657314, 0.0688102701912684,
        0.05661360645200331, 0.4064015857717699],
       ...,
       [0.28909951295055936, 0.46355128612119056, 0.9720755182885633,
        0.46418074435243006, 0.5360910733233925],
       [0.0040906300461485134, 0.9939664743748178, 0.8110287166002298,
        0.6629817780476059, 0.7828334824689192],
       [0.005442375425016244, 0.3906156641523768, 0.23137442328510927,
        0.6935151082046206, 0.5618167909645311]],
      shape=(334, 5), dtype=object)

In [192]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.217226,0.599351,0.125551,0.550419,0.549868,0.12855,0.036296,0.543037,0.285687,...,0.538581,0.593282,0.295264,0.152216,0.615937,0.689214,0.003318,0.2891,0.004091,0.005442
1,0.760962,0.944573,0.170901,0.004809,0.627881,0.354201,0.429673,0.851018,0.98358,0.109425,...,0.368004,0.154691,0.132984,0.523598,0.695697,0.678076,0.809338,0.463551,0.993966,0.390616
2,0.813566,0.753998,0.06881,0.28147,0.553374,0.797741,0.650676,0.178784,0.428069,0.826344,...,0.575524,0.322539,0.437211,0.89405,0.761673,0.502699,0.243238,0.972076,0.811029,0.231374
3,0.710205,0.552001,0.056614,0.678613,0.510162,0.828498,0.871598,0.742298,0.294458,0.291752,...,0.538747,0.060439,0.106983,0.156294,0.296572,0.449758,0.591304,0.464181,0.662982,0.693515
4,0.566004,0.182937,0.406402,0.159748,0.529592,0.65623,0.445874,0.069187,0.881423,0.648689,...,0.554512,0.589997,0.22613,0.95589,0.212751,0.80457,0.714628,0.536091,0.782833,0.561817

In [193]:
newdf.head()

          0         1         2         3         4
0     groot  0.760962  0.813566  0.710205  0.566004
1  0.217226  0.944573  0.753998  0.552001  0.182937
2  0.599351  0.170901  0.068810  0.056614  0.406402
3  0.125551  0.004809  0.281470  0.678613  0.159748
4  0.550419  0.627881  0.553374  0.510162  0.529592

In [194]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.005442  0.390616  0.231374  0.693515  0.561817
332  0.004091  0.993966  0.811029  0.662982  0.782833
331    0.2891  0.463551  0.972076  0.464181  0.536091
330  0.003318  0.809338  0.243238  0.591304  0.714628
329  0.689214  0.678076  0.502699  0.449758  0.804570
..        ...       ...       ...       ...       ...
4    0.550419  0.627881  0.553374  0.510162  0.529592
3    0.125551  0.004809  0.281470  0.678613  0.159748
2    0.599351  0.170901  0.068810  0.056614  0.406402
1    0.217226  0.944573  0.753998  0.552001  0.182937
0       groot  0.760962  0.813566  0.710205  0.566004

[334 rows x 5 columns]

In [195]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.566004  0.710205  0.813566  0.760962     groot
1    0.182937  0.552001  0.753998  0.944573  0.217226
2    0.406402  0.056614  0.068810  0.170901  0.599351
3    0.159748  0.678613  0.281470  0.004809  0.125551
4    0.529592  0.510162  0.553374  0.627881  0.550419
..        ...       ...       ...       ...       ...
329  0.804570  0.449758  0.502699  0.678076  0.689214
330  0.714628  0.591304  0.243238  0.809338  0.003318
331  0.536091  0.464181  0.972076  0.463551    0.2891
332  0.782833  0.662982  0.811029  0.993966  0.004091
333  0.561817  0.693515  0.231374  0.390616  0.005442

[334 rows x 5 columns]

In [196]:
newdf[0]

0         groot
1      0.217226
2      0.599351
3      0.125551
4      0.550419
         ...
329    0.689214
330    0.003318
331      0.2891
332    0.004091
333    0.005442
Name: 0, Length: 334, dtype: object

In [197]:
type(newdf[0])

pandas.Series

In [198]:
# newdf2=newdf.copy()

In [ ]:
newdf.loc[0,0] = 95

In [200]:
newdf

            0         1         2         3         4  (0, 0)
0       groot  0.760962  0.813566  0.710205  0.566004      95
1    0.217226  0.944573  0.753998  0.552001  0.182937      95
2    0.599351  0.170901  0.068810  0.056614  0.406402      95
3    0.125551  0.004809  0.281470  0.678613  0.159748      95
4    0.550419  0.627881  0.553374  0.510162  0.529592      95
..        ...       ...       ...       ...       ...     ...
329  0.689214  0.678076  0.502699  0.449758  0.804570      95
330  0.003318  0.809338  0.243238  0.591304  0.714628      95
331    0.2891  0.463551  0.972076  0.464181  0.536091      95
332  0.004091  0.993966  0.811029  0.662982  0.782833      95
333  0.005442  0.390616  0.231374  0.693515  0.561817      95

[334 rows x 6 columns]

In [201]:
# newdf.loc[0,0]=980
# newdf.head(7)