# PANDAS

In [68]:
import numpy as np 
import pandas as pd

In [69]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [70]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [71]:
df.to_csv('F20file1.csv')

In [72]:
df.to_csv('F20file2.csv',index=False)

In [73]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [74]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [75]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [76]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [77]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [78]:
z['name'][0]

'F-22'

In [79]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [80]:
#z.to_csv('F20file3.csv')

In [81]:
ser=pd.Series(np.random.rand(10))
ser

0    0.261351
1    0.539487
2    0.562031
3    0.707713
4    0.185895
5    0.825945
6    0.767908
7    0.680385
8    0.671633
9    0.306440
dtype: float64

In [82]:
type(ser)

pandas.Series

In [83]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.967119  0.791247  0.427550  0.025182  0.355663
1  0.655175  0.238060  0.353134  0.344448  0.115948
2  0.585218  0.470219  0.780847  0.680516  0.148712
3  0.249781  0.743828  0.254798  0.083857  0.214305
4  0.137018  0.910879  0.107700  0.565779  0.261267

In [84]:
type(newdf)

pandas.DataFrame

In [85]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.490355    0.485866    0.495743    0.502344    0.520700
std      0.292958    0.277645    0.283687    0.298923    0.293228
min      0.000660    0.006698    0.000345    0.000450    0.006427
25%      0.226378    0.229417    0.256347    0.232429    0.270698
50%      0.511475    0.475987    0.495765    0.497896    0.484974
75%      0.737939    0.721374    0.737332    0.762877    0.784916
max      0.997123    0.998842    0.998035    0.998452    0.997302

In [86]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [87]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [88]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [89]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [90]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [91]:
newdf.to_numpy()

array([['groot', 0.7912472028843491, 0.4275501367543364,
        0.025181797322507804, 0.3556629039818654],
       [0.6551750781478942, 0.23806021895134488, 0.3531337296468644,
        0.3444483278273909, 0.11594813697051543],
       [0.585218000546686, 0.4702188994260197, 0.78084685225214,
        0.6805155369885831, 0.1487116547826024],
       ...,
       [0.01817523906227625, 0.5279859131423199, 0.8404344203073212,
        0.4720632504052782, 0.9458794932198361],
       [0.3829135761793875, 0.48189914465776296, 0.5139369447606621,
        0.7831407994800794, 0.8382307916659739],
       [0.8635850601777529, 0.20234249958753536, 0.0884866841990185,
        0.09688240687570837, 0.9900826280273897]],
      shape=(334, 5), dtype=object)

In [92]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.655175,0.585218,0.249781,0.137018,0.416119,0.607922,0.984019,0.516009,0.236382,...,0.675488,0.274338,0.306049,0.60464,0.95653,0.554383,0.794592,0.018175,0.382914,0.863585
1,0.791247,0.23806,0.470219,0.743828,0.910879,0.526643,0.580899,0.73484,0.78457,0.314939,...,0.534258,0.57438,0.065425,0.144081,0.439158,0.534622,0.564456,0.527986,0.481899,0.202342
2,0.42755,0.353134,0.780847,0.254798,0.1077,0.182327,0.743681,0.070101,0.461859,0.65529,...,0.998035,0.325,0.637388,0.713132,0.834733,0.808858,0.126646,0.840434,0.513937,0.088487
3,0.025182,0.344448,0.680516,0.083857,0.565779,0.123278,0.604575,0.086922,0.949192,0.701775,...,0.861839,0.165602,0.732822,0.863663,0.53203,0.255783,0.580119,0.472063,0.783141,0.096882
4,0.355663,0.115948,0.148712,0.214305,0.261267,0.053908,0.621075,0.529413,0.824636,0.465554,...,0.731281,0.455121,0.377928,0.847306,0.614594,0.245648,0.313537,0.945879,0.838231,0.990083

In [93]:
newdf.head()

          0         1         2         3         4
0     groot  0.791247  0.427550  0.025182  0.355663
1  0.655175  0.238060  0.353134  0.344448  0.115948
2  0.585218  0.470219  0.780847  0.680516  0.148712
3  0.249781  0.743828  0.254798  0.083857  0.214305
4  0.137018  0.910879  0.107700  0.565779  0.261267

In [94]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.863585  0.202342  0.088487  0.096882  0.990083
332  0.382914  0.481899  0.513937  0.783141  0.838231
331  0.018175  0.527986  0.840434  0.472063  0.945879
330  0.794592  0.564456  0.126646  0.580119  0.313537
329  0.554383  0.534622  0.808858  0.255783  0.245648
..        ...       ...       ...       ...       ...
4    0.137018  0.910879  0.107700  0.565779  0.261267
3    0.249781  0.743828  0.254798  0.083857  0.214305
2    0.585218  0.470219  0.780847  0.680516  0.148712
1    0.655175  0.238060  0.353134  0.344448  0.115948
0       groot  0.791247  0.427550  0.025182  0.355663

[334 rows x 5 columns]

In [95]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.355663  0.025182  0.427550  0.791247     groot
1    0.115948  0.344448  0.353134  0.238060  0.655175
2    0.148712  0.680516  0.780847  0.470219  0.585218
3    0.214305  0.083857  0.254798  0.743828  0.249781
4    0.261267  0.565779  0.107700  0.910879  0.137018
..        ...       ...       ...       ...       ...
329  0.245648  0.255783  0.808858  0.534622  0.554383
330  0.313537  0.580119  0.126646  0.564456  0.794592
331  0.945879  0.472063  0.840434  0.527986  0.018175
332  0.838231  0.783141  0.513937  0.481899  0.382914
333  0.990083  0.096882  0.088487  0.202342  0.863585

[334 rows x 5 columns]

In [96]:
newdf[0]

0         groot
1      0.655175
2      0.585218
3      0.249781
4      0.137018
         ...
329    0.554383
330    0.794592
331    0.018175
332    0.382914
333    0.863585
Name: 0, Length: 334, dtype: object

In [97]:
type(newdf[0])

pandas.Series

In [ ]:
# newdf2=newdf.copy()

In [119]:
newdf[0,0] = 95

In [125]:
newdf

            0         1         2         3         4  (0, 0)
0         980  0.791247  0.427550  0.025182  0.355663      95
1    0.655175  0.238060  0.353134  0.344448  0.115948      95
2    0.585218  0.470219  0.780847  0.680516  0.148712      95
3    0.249781  0.743828  0.254798  0.083857  0.214305      95
4    0.137018  0.910879  0.107700  0.565779  0.261267      95
..        ...       ...       ...       ...       ...     ...
329  0.554383  0.534622  0.808858  0.255783  0.245648      95
330  0.794592  0.564456  0.126646  0.580119  0.313537      95
331  0.018175  0.527986  0.840434  0.472063  0.945879      95
332  0.382914  0.481899  0.513937  0.783141  0.838231      95
333  0.863585  0.202342  0.088487  0.096882  0.990083      95

[334 rows x 6 columns]

In [107]:
newdf.loc[0,0]=980
newdf.head(7)

          0         1         2         3         4
0       980  0.791247  0.427550  0.025182  0.355663
1  0.655175  0.238060  0.353134  0.344448  0.115948
2  0.585218  0.470219  0.780847  0.680516  0.148712
3  0.249781  0.743828  0.254798  0.083857  0.214305
4  0.137018  0.910879  0.107700  0.565779  0.261267
5  0.416119  0.526643  0.182327  0.123278  0.053908
6  0.607922  0.580899  0.743681  0.604575  0.621075