# PANDAS

In [2]:
import numpy as np 
import pandas as pd

In [3]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [4]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [5]:
df.to_csv('F20file1.csv')

In [6]:
df.to_csv('F20file2.csv',index=False)

In [7]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [8]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [9]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [10]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [11]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [12]:
z['name'][0]

'F-22'

In [13]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [14]:
#z.to_csv('F20file3.csv')

In [15]:
ser=pd.Series(np.random.rand(10))
ser

0    0.283272
1    0.499491
2    0.373003
3    0.770655
4    0.695139
5    0.581865
6    0.645731
7    0.126435
8    0.872892
9    0.881537
dtype: float64

In [16]:
type(ser)

pandas.Series

In [17]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.311378  0.812277  0.163240  0.142838  0.710900
1  0.014292  0.338424  0.494162  0.294058  0.029311
2  0.053428  0.731876  0.540189  0.174996  0.784313
3  0.605210  0.357293  0.509909  0.316194  0.508073
4  0.773346  0.771944  0.204954  0.475927  0.413607

In [18]:
type(newdf)

pandas.DataFrame

In [19]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.492206    0.510580    0.512444    0.487116    0.486203
std      0.292982    0.274552    0.290151    0.289574    0.290622
min      0.001325    0.011540    0.010684    0.000813    0.001314
25%      0.244476    0.301198    0.262435    0.221047    0.223436
50%      0.475057    0.516686    0.526549    0.463320    0.487321
75%      0.745339    0.732832    0.768257    0.748769    0.736006
max      0.994793    0.993313    0.999622    0.996380    0.995256

In [20]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [21]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [22]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [23]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [24]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [25]:
newdf.to_numpy()

array([['groot', 0.812276936640539, 0.163240167929657,
        0.1428383188261303, 0.7108995672639206],
       [0.0142919443723879, 0.3384235029165563, 0.4941621906868944,
        0.2940581130666541, 0.029311215791849032],
       [0.05342779879720594, 0.7318758616103166, 0.5401890799842224,
        0.1749956340606572, 0.7843125094262077],
       ...,
       [0.10603959704311938, 0.3037854425202251, 0.6712525233117669,
        0.11817705769927767, 0.17839314133502238],
       [0.11378935744442542, 0.6955520881096354, 0.4003452885416299,
        0.8809202462610365, 0.8145952170413491],
       [0.30704433327444536, 0.853717345187849, 0.7683333774916665,
        0.8415454531677046, 0.4303018440017974]],
      shape=(334, 5), dtype=object)

In [26]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.014292,0.053428,0.60521,0.773346,0.478279,0.899844,0.504229,0.968089,0.399476,...,0.952304,0.236129,0.658669,0.899078,0.670611,0.251215,0.324797,0.10604,0.113789,0.307044
1,0.812277,0.338424,0.731876,0.357293,0.771944,0.589966,0.849789,0.367523,0.342949,0.388397,...,0.46967,0.561768,0.819836,0.539041,0.640914,0.234632,0.708813,0.303785,0.695552,0.853717
2,0.16324,0.494162,0.540189,0.509909,0.204954,0.28308,0.310434,0.410827,0.804028,0.042787,...,0.901308,0.041226,0.640566,0.087353,0.922706,0.578235,0.908097,0.671253,0.400345,0.768333
3,0.142838,0.294058,0.174996,0.316194,0.475927,0.967321,0.364783,0.709254,0.45043,0.068872,...,0.744837,0.54505,0.33677,0.821176,0.131597,0.28755,0.549182,0.118177,0.88092,0.841545
4,0.7109,0.029311,0.784313,0.508073,0.413607,0.073707,0.225474,0.107605,0.656994,0.478806,...,0.151421,0.106477,0.247874,0.597149,0.995256,0.645889,0.725055,0.178393,0.814595,0.430302

In [27]:
newdf.head()

          0         1         2         3         4
0     groot  0.812277  0.163240  0.142838  0.710900
1  0.014292  0.338424  0.494162  0.294058  0.029311
2  0.053428  0.731876  0.540189  0.174996  0.784313
3   0.60521  0.357293  0.509909  0.316194  0.508073
4  0.773346  0.771944  0.204954  0.475927  0.413607

In [28]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.307044  0.853717  0.768333  0.841545  0.430302
332  0.113789  0.695552  0.400345  0.880920  0.814595
331   0.10604  0.303785  0.671253  0.118177  0.178393
330  0.324797  0.708813  0.908097  0.549182  0.725055
329  0.251215  0.234632  0.578235  0.287550  0.645889
..        ...       ...       ...       ...       ...
4    0.773346  0.771944  0.204954  0.475927  0.413607
3     0.60521  0.357293  0.509909  0.316194  0.508073
2    0.053428  0.731876  0.540189  0.174996  0.784313
1    0.014292  0.338424  0.494162  0.294058  0.029311
0       groot  0.812277  0.163240  0.142838  0.710900

[334 rows x 5 columns]

In [29]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.710900  0.142838  0.163240  0.812277     groot
1    0.029311  0.294058  0.494162  0.338424  0.014292
2    0.784313  0.174996  0.540189  0.731876  0.053428
3    0.508073  0.316194  0.509909  0.357293   0.60521
4    0.413607  0.475927  0.204954  0.771944  0.773346
..        ...       ...       ...       ...       ...
329  0.645889  0.287550  0.578235  0.234632  0.251215
330  0.725055  0.549182  0.908097  0.708813  0.324797
331  0.178393  0.118177  0.671253  0.303785   0.10604
332  0.814595  0.880920  0.400345  0.695552  0.113789
333  0.430302  0.841545  0.768333  0.853717  0.307044

[334 rows x 5 columns]

In [30]:
newdf[0]

0         groot
1      0.014292
2      0.053428
3       0.60521
4      0.773346
         ...
329    0.251215
330    0.324797
331     0.10604
332    0.113789
333    0.307044
Name: 0, Length: 334, dtype: object

In [31]:
type(newdf[0])

pandas.Series

In [32]:
newdf2=newdf.copy()

In [33]:
newdf.loc[0,0] = 95

In [34]:
newdf

            0         1         2         3         4
0          95  0.812277  0.163240  0.142838  0.710900
1    0.014292  0.338424  0.494162  0.294058  0.029311
2    0.053428  0.731876  0.540189  0.174996  0.784313
3     0.60521  0.357293  0.509909  0.316194  0.508073
4    0.773346  0.771944  0.204954  0.475927  0.413607
..        ...       ...       ...       ...       ...
329  0.251215  0.234632  0.578235  0.287550  0.645889
330  0.324797  0.708813  0.908097  0.549182  0.725055
331   0.10604  0.303785  0.671253  0.118177  0.178393
332  0.113789  0.695552  0.400345  0.880920  0.814595
333  0.307044  0.853717  0.768333  0.841545  0.430302

[334 rows x 5 columns]

In [35]:
newdf.loc[0,0]=980
newdf.head(7)

          0         1         2         3         4
0       980  0.812277  0.163240  0.142838  0.710900
1  0.014292  0.338424  0.494162  0.294058  0.029311
2  0.053428  0.731876  0.540189  0.174996  0.784313
3   0.60521  0.357293  0.509909  0.316194  0.508073
4  0.773346  0.771944  0.204954  0.475927  0.413607
5  0.478279  0.589966  0.283080  0.967321  0.073707
6  0.899844  0.849789  0.310434  0.364783  0.225474

In [36]:
newdf.columns=list("ABCDE")
newdf

            A         B         C         D         E
0         980  0.812277  0.163240  0.142838  0.710900
1    0.014292  0.338424  0.494162  0.294058  0.029311
2    0.053428  0.731876  0.540189  0.174996  0.784313
3     0.60521  0.357293  0.509909  0.316194  0.508073
4    0.773346  0.771944  0.204954  0.475927  0.413607
..        ...       ...       ...       ...       ...
329  0.251215  0.234632  0.578235  0.287550  0.645889
330  0.324797  0.708813  0.908097  0.549182  0.725055
331   0.10604  0.303785  0.671253  0.118177  0.178393
332  0.113789  0.695552  0.400345  0.880920  0.814595
333  0.307044  0.853717  0.768333  0.841545  0.430302

[334 rows x 5 columns]

In [37]:
newdf.loc[0,0]=990

In [38]:
newdf.head()

          A         B         C         D         E      0
0       980  0.812277  0.163240  0.142838  0.710900  990.0
1  0.014292  0.338424  0.494162  0.294058  0.029311    NaN
2  0.053428  0.731876  0.540189  0.174996  0.784313    NaN
3   0.60521  0.357293  0.509909  0.316194  0.508073    NaN
4  0.773346  0.771944  0.204954  0.475927  0.413607    NaN

In [39]:
newdf = newdf.drop(0, axis=1)
newdf.head()

          A         B         C         D         E
0       980  0.812277  0.163240  0.142838  0.710900
1  0.014292  0.338424  0.494162  0.294058  0.029311
2  0.053428  0.731876  0.540189  0.174996  0.784313
3   0.60521  0.357293  0.509909  0.316194  0.508073
4  0.773346  0.771944  0.204954  0.475927  0.413607

In [40]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.494162  0.294058
2  0.540189  0.174996

In [41]:
newdf.loc[:,['C','D']]

            C         D
0    0.163240  0.142838
1    0.494162  0.294058
2    0.540189  0.174996
3    0.509909  0.316194
4    0.204954  0.475927
..        ...       ...
329  0.578235  0.287550
330  0.908097  0.549182
331  0.671253  0.118177
332  0.400345  0.880920
333  0.768333  0.841545

[334 rows x 2 columns]

In [42]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.014292  0.338424  0.494162  0.294058  0.029311
2  0.053428  0.731876  0.540189  0.174996  0.784313

In [43]:
newdf.loc[(newdf['A']<0.3)&(newdf['C']>0.1)]

            A         B         C         D         E
1    0.014292  0.338424  0.494162  0.294058  0.029311
2    0.053428  0.731876  0.540189  0.174996  0.784313
13   0.220369  0.162754  0.541145  0.606607  0.721050
16   0.045002  0.990318  0.580479  0.897273  0.460762
17   0.148402  0.667535  0.621482  0.880789  0.472907
..        ...       ...       ...       ...       ...
312  0.142024  0.063213  0.821100  0.066532  0.737663
323  0.118527  0.245455  0.210457  0.104389  0.129703
329  0.251215  0.234632  0.578235  0.287550  0.645889
331   0.10604  0.303785  0.671253  0.118177  0.178393
332  0.113789  0.695552  0.400345  0.880920  0.814595

[87 rows x 5 columns]

In [44]:
newdf.iloc[0,4]

np.float64(0.7108995672639206)

In [45]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.812277  0.163240
1  0.338424  0.494162

In [46]:
newdf.head(3)

          A         B         C         D         E
0       980  0.812277  0.163240  0.142838  0.710900
1  0.014292  0.338424  0.494162  0.294058  0.029311
2  0.053428  0.731876  0.540189  0.174996  0.784313

In [47]:
newdf.drop([0])

            A         B         C         D         E
1    0.014292  0.338424  0.494162  0.294058  0.029311
2    0.053428  0.731876  0.540189  0.174996  0.784313
3     0.60521  0.357293  0.509909  0.316194  0.508073
4    0.773346  0.771944  0.204954  0.475927  0.413607
5    0.478279  0.589966  0.283080  0.967321  0.073707
..        ...       ...       ...       ...       ...
329  0.251215  0.234632  0.578235  0.287550  0.645889
330  0.324797  0.708813  0.908097  0.549182  0.725055
331   0.10604  0.303785  0.671253  0.118177  0.178393
332  0.113789  0.695552  0.400345  0.880920  0.814595
333  0.307044  0.853717  0.768333  0.841545  0.430302

[333 rows x 5 columns]

In [48]:
newdf.drop(['A','C'],axis=1)

            B         D         E
0    0.812277  0.142838  0.710900
1    0.338424  0.294058  0.029311
2    0.731876  0.174996  0.784313
3    0.357293  0.316194  0.508073
4    0.771944  0.475927  0.413607
..        ...       ...       ...
329  0.234632  0.287550  0.645889
330  0.708813  0.549182  0.725055
331  0.303785  0.118177  0.178393
332  0.695552  0.880920  0.814595
333  0.853717  0.841545  0.430302

[334 rows x 3 columns]

In [49]:
newdf.drop(['D','E'],axis=1, inplace=True)

In [50]:
newdf

            A         B         C
0         980  0.812277  0.163240
1    0.014292  0.338424  0.494162
2    0.053428  0.731876  0.540189
3     0.60521  0.357293  0.509909
4    0.773346  0.771944  0.204954
..        ...       ...       ...
329  0.251215  0.234632  0.578235
330  0.324797  0.708813  0.908097
331   0.10604  0.303785  0.671253
332  0.113789  0.695552  0.400345
333  0.307044  0.853717  0.768333

[334 rows x 3 columns]

In [51]:
newdf.reset_index(drop=True, inplace=True)
newdf.head(3)

          A         B         C
0       980  0.812277  0.163240
1  0.014292  0.338424  0.494162
2  0.053428  0.731876  0.540189

In [52]:
newdf['B']=None

In [53]:
newdf

            A     B         C
0         980  None  0.163240
1    0.014292  None  0.494162
2    0.053428  None  0.540189
3     0.60521  None  0.509909
4    0.773346  None  0.204954
..        ...   ...       ...
329  0.251215  None  0.578235
330  0.324797  None  0.908097
331   0.10604  None  0.671253
332  0.113789  None  0.400345
333  0.307044  None  0.768333

[334 rows x 3 columns]

In [54]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
329    True
330    True
331    True
332    True
333    True
Name: B, Length: 334, dtype: bool

In [55]:
newdf.loc[:,['B']]=90
newdf

            A   B         C
0         980  90  0.163240
1    0.014292  90  0.494162
2    0.053428  90  0.540189
3     0.60521  90  0.509909
4    0.773346  90  0.204954
..        ...  ..       ...
329  0.251215  90  0.578235
330  0.324797  90  0.908097
331   0.10604  90  0.671253
332  0.113789  90  0.400345
333  0.307044  90  0.768333

[334 rows x 3 columns]

In [56]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       334 non-null    object
 1   B       334 non-null    object
 2   C       334 non-null    float64
dtypes: float64(1), object(2)
memory usage: 8.0+ KB

In [57]:
newdf.notnull()

        A     B     C
0    True  True  True
1    True  True  True
2    True  True  True
3    True  True  True
4    True  True  True
..    ...   ...   ...
329  True  True  True
330  True  True  True
331  True  True  True
332  True  True  True
333  True  True  True

[334 rows x 3 columns]

In [ ]:

data=pd.read_excel('F20file4.xlsx')

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.