# PANDAS

In [64]:
import numpy as np 
import pandas as pd

In [65]:
dict1={
    "name":['Tom','Groot','Rocket','Thanos'],
    "marks":[92,72,64,89],
    "city":["New York","New Delhi","London","Berlin"]
}

In [66]:
df=pd.DataFrame(dict1)
df

     name  marks       city
0     Tom     92   New York
1   Groot     72  New Delhi
2  Rocket     64     London
3  Thanos     89     Berlin

In [67]:
df.to_csv('F20file1.csv')

In [68]:
df.to_csv('F20file2.csv',index=False)

In [69]:
df.head(2)

    name  marks       city
0    Tom     92   New York
1  Groot     72  New Delhi

In [70]:
df.tail(2)

     name  marks    city
2  Rocket     64  London
3  Thanos     89  Berlin

In [71]:
df.describe()

           marks
count   4.000000
mean   79.250000
std    13.450527
min    64.000000
25%    70.000000
50%    80.500000
75%    89.750000
max    92.000000

In [72]:
z=pd.read_csv('F20file3.csv')
z

  Unnamed: 0   name generations Country
0      first   F-22         5th     USA
1     second  SU-57         5th  Russia
2      third   J-20         5th   China
3     fourth   F-35         5th     USA

In [73]:
z['name']

0     F-22
1    SU-57
2     J-20
3     F-35
Name: name, dtype: str

In [74]:
z['name'][0]

'F-22'

In [75]:
z.index=['first','second','third','fourth']
z

       Unnamed: 0   name generations Country
first       first   F-22         5th     USA
second     second  SU-57         5th  Russia
third       third   J-20         5th   China
fourth     fourth   F-35         5th     USA

In [76]:
#z.to_csv('F20file3.csv')

In [77]:
ser=pd.Series(np.random.rand(10))
ser

0    0.267199
1    0.259508
2    0.018649
3    0.975770
4    0.821499
5    0.688693
6    0.785926
7    0.444997
8    0.258402
9    0.367601
dtype: float64

In [78]:
type(ser)

pandas.Series

In [79]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
newdf.head()

          0         1         2         3         4
0  0.362622  0.935295  0.586612  0.389377  0.236715
1  0.991158  0.139270  0.814556  0.170881  0.299616
2  0.943957  0.276038  0.841544  0.922318  0.509565
3  0.585182  0.849374  0.489625  0.221360  0.357193
4  0.254445  0.549811  0.463228  0.162912  0.835231

In [80]:
type(newdf)

pandas.DataFrame

In [81]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.512055    0.513466    0.504883    0.487035    0.500214
std      0.294227    0.298104    0.284156    0.292757    0.280116
min      0.000267    0.000702    0.001979    0.002559    0.001318
25%      0.259819    0.256114    0.265395    0.237863    0.259094
50%      0.528110    0.549561    0.502103    0.465683    0.496395
75%      0.750331    0.766555    0.757518    0.740599    0.754567
max      0.999798    0.996257    0.996394    0.998556    0.993325

In [82]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [83]:
newdf[0] = newdf[0].astype(object)
newdf.loc[0, 0] = "groot"

In [84]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [85]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [86]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [87]:
newdf.to_numpy()

array([['groot', 0.9352946101229923, 0.5866119637145716,
        0.38937713428013043, 0.2367146803161705],
       [0.9911580493486394, 0.13927045273562688, 0.81455570879675,
        0.17088125930262643, 0.2996164219140889],
       [0.9439571886617099, 0.2760375742045863, 0.8415444012450725,
        0.9223178858370578, 0.5095652492752792],
       ...,
       [0.2807456211837308, 0.015571033212215979, 0.09350983722987893,
        0.14419999474731582, 0.9327663494683398],
       [0.9856849274878595, 0.1852510689021959, 0.9851737666946124,
        0.9155278108666803, 0.011104097992034934],
       [0.24603035413879248, 0.9433941145361984, 0.5307594246369227,
        0.2396674411290285, 0.8475593631392329]],
      shape=(334, 5), dtype=object)

In [88]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,groot,0.991158,0.943957,0.585182,0.254445,0.808136,0.946213,0.325512,0.400313,0.850559,...,0.412944,0.84364,0.290361,0.168982,0.732233,0.983074,0.733364,0.280746,0.985685,0.24603
1,0.935295,0.13927,0.276038,0.849374,0.549811,0.37415,0.657754,0.986542,0.860919,0.170687,...,0.145106,0.025725,0.428196,0.273811,0.054633,0.971063,0.309182,0.015571,0.185251,0.943394
2,0.586612,0.814556,0.841544,0.489625,0.463228,0.361725,0.139774,0.189449,0.129747,0.706597,...,0.366787,0.032035,0.758552,0.369649,0.876986,0.946773,0.665807,0.09351,0.985174,0.530759
3,0.389377,0.170881,0.922318,0.22136,0.162912,0.520227,0.449932,0.065767,0.103214,0.870485,...,0.458445,0.361168,0.772688,0.119482,0.324506,0.672985,0.574723,0.1442,0.915528,0.239667
4,0.236715,0.299616,0.509565,0.357193,0.835231,0.01813,0.494872,0.102632,0.624774,0.428174,...,0.910293,0.276676,0.721634,0.481889,0.692865,0.580792,0.475547,0.932766,0.011104,0.847559

In [89]:
newdf.head()

          0         1         2         3         4
0     groot  0.935295  0.586612  0.389377  0.236715
1  0.991158  0.139270  0.814556  0.170881  0.299616
2  0.943957  0.276038  0.841544  0.922318  0.509565
3  0.585182  0.849374  0.489625  0.221360  0.357193
4  0.254445  0.549811  0.463228  0.162912  0.835231

In [90]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333   0.24603  0.943394  0.530759  0.239667  0.847559
332  0.985685  0.185251  0.985174  0.915528  0.011104
331  0.280746  0.015571  0.093510  0.144200  0.932766
330  0.733364  0.309182  0.665807  0.574723  0.475547
329  0.983074  0.971063  0.946773  0.672985  0.580792
..        ...       ...       ...       ...       ...
4    0.254445  0.549811  0.463228  0.162912  0.835231
3    0.585182  0.849374  0.489625  0.221360  0.357193
2    0.943957  0.276038  0.841544  0.922318  0.509565
1    0.991158  0.139270  0.814556  0.170881  0.299616
0       groot  0.935295  0.586612  0.389377  0.236715

[334 rows x 5 columns]

In [91]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.236715  0.389377  0.586612  0.935295     groot
1    0.299616  0.170881  0.814556  0.139270  0.991158
2    0.509565  0.922318  0.841544  0.276038  0.943957
3    0.357193  0.221360  0.489625  0.849374  0.585182
4    0.835231  0.162912  0.463228  0.549811  0.254445
..        ...       ...       ...       ...       ...
329  0.580792  0.672985  0.946773  0.971063  0.983074
330  0.475547  0.574723  0.665807  0.309182  0.733364
331  0.932766  0.144200  0.093510  0.015571  0.280746
332  0.011104  0.915528  0.985174  0.185251  0.985685
333  0.847559  0.239667  0.530759  0.943394   0.24603

[334 rows x 5 columns]

In [92]:
newdf[0]

0         groot
1      0.991158
2      0.943957
3      0.585182
4      0.254445
         ...
329    0.983074
330    0.733364
331    0.280746
332    0.985685
333     0.24603
Name: 0, Length: 334, dtype: object

In [93]:
type(newdf[0])

pandas.Series

In [94]:
newdf2=newdf.copy()

In [95]:
newdf.loc[0,0] = 95

In [96]:
newdf

            0         1         2         3         4
0          95  0.935295  0.586612  0.389377  0.236715
1    0.991158  0.139270  0.814556  0.170881  0.299616
2    0.943957  0.276038  0.841544  0.922318  0.509565
3    0.585182  0.849374  0.489625  0.221360  0.357193
4    0.254445  0.549811  0.463228  0.162912  0.835231
..        ...       ...       ...       ...       ...
329  0.983074  0.971063  0.946773  0.672985  0.580792
330  0.733364  0.309182  0.665807  0.574723  0.475547
331  0.280746  0.015571  0.093510  0.144200  0.932766
332  0.985685  0.185251  0.985174  0.915528  0.011104
333   0.24603  0.943394  0.530759  0.239667  0.847559

[334 rows x 5 columns]

In [97]:
newdf.loc[0,0]=980
newdf.head(7)

          0         1         2         3         4
0       980  0.935295  0.586612  0.389377  0.236715
1  0.991158  0.139270  0.814556  0.170881  0.299616
2  0.943957  0.276038  0.841544  0.922318  0.509565
3  0.585182  0.849374  0.489625  0.221360  0.357193
4  0.254445  0.549811  0.463228  0.162912  0.835231
5  0.808136  0.374150  0.361725  0.520227  0.018130
6  0.946213  0.657754  0.139774  0.449932  0.494872

In [98]:
newdf.columns=list("ABCDE")
newdf

            A         B         C         D         E
0         980  0.935295  0.586612  0.389377  0.236715
1    0.991158  0.139270  0.814556  0.170881  0.299616
2    0.943957  0.276038  0.841544  0.922318  0.509565
3    0.585182  0.849374  0.489625  0.221360  0.357193
4    0.254445  0.549811  0.463228  0.162912  0.835231
..        ...       ...       ...       ...       ...
329  0.983074  0.971063  0.946773  0.672985  0.580792
330  0.733364  0.309182  0.665807  0.574723  0.475547
331  0.280746  0.015571  0.093510  0.144200  0.932766
332  0.985685  0.185251  0.985174  0.915528  0.011104
333   0.24603  0.943394  0.530759  0.239667  0.847559

[334 rows x 5 columns]

In [99]:
newdf.loc[0,0]=990

In [100]:
newdf.head()

          A         B         C         D         E      0
0       980  0.935295  0.586612  0.389377  0.236715  990.0
1  0.991158  0.139270  0.814556  0.170881  0.299616    NaN
2  0.943957  0.276038  0.841544  0.922318  0.509565    NaN
3  0.585182  0.849374  0.489625  0.221360  0.357193    NaN
4  0.254445  0.549811  0.463228  0.162912  0.835231    NaN

In [101]:
newdf = newdf.drop(0, axis=1)
newdf.head()

          A         B         C         D         E
0       980  0.935295  0.586612  0.389377  0.236715
1  0.991158  0.139270  0.814556  0.170881  0.299616
2  0.943957  0.276038  0.841544  0.922318  0.509565
3  0.585182  0.849374  0.489625  0.221360  0.357193
4  0.254445  0.549811  0.463228  0.162912  0.835231

In [102]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.814556  0.170881
2  0.841544  0.922318

In [103]:
newdf.loc[:,['C','D']]

            C         D
0    0.586612  0.389377
1    0.814556  0.170881
2    0.841544  0.922318
3    0.489625  0.221360
4    0.463228  0.162912
..        ...       ...
329  0.946773  0.672985
330  0.665807  0.574723
331  0.093510  0.144200
332  0.985174  0.915528
333  0.530759  0.239667

[334 rows x 2 columns]

In [104]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.991158  0.139270  0.814556  0.170881  0.299616
2  0.943957  0.276038  0.841544  0.922318  0.509565

In [105]:
newdf.loc[(newdf['A']<0.3)&(newdf['C']>0.1)]

            A         B         C         D         E
4    0.254445  0.549811  0.463228  0.162912  0.835231
13   0.247459  0.728112  0.540864  0.853274  0.129543
17    0.22042  0.018026  0.875898  0.137135  0.441877
18   0.166693  0.735970  0.948462  0.840582  0.515662
25   0.283422  0.396833  0.400675  0.875805  0.522642
..        ...       ...       ...       ...       ...
317  0.055438  0.477494  0.823872  0.830427  0.850402
320   0.27765  0.533700  0.757526  0.894042  0.496513
326  0.290361  0.428196  0.758552  0.772688  0.721634
327  0.168982  0.273811  0.369649  0.119482  0.481889
333   0.24603  0.943394  0.530759  0.239667  0.847559

[88 rows x 5 columns]

In [106]:
newdf.iloc[0,4]

np.float64(0.2367146803161705)

In [107]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.935295  0.586612
1  0.139270  0.814556

In [108]:
newdf.head(3)

          A         B         C         D         E
0       980  0.935295  0.586612  0.389377  0.236715
1  0.991158  0.139270  0.814556  0.170881  0.299616
2  0.943957  0.276038  0.841544  0.922318  0.509565

In [109]:
newdf.drop([0])

            A         B         C         D         E
1    0.991158  0.139270  0.814556  0.170881  0.299616
2    0.943957  0.276038  0.841544  0.922318  0.509565
3    0.585182  0.849374  0.489625  0.221360  0.357193
4    0.254445  0.549811  0.463228  0.162912  0.835231
5    0.808136  0.374150  0.361725  0.520227  0.018130
..        ...       ...       ...       ...       ...
329  0.983074  0.971063  0.946773  0.672985  0.580792
330  0.733364  0.309182  0.665807  0.574723  0.475547
331  0.280746  0.015571  0.093510  0.144200  0.932766
332  0.985685  0.185251  0.985174  0.915528  0.011104
333   0.24603  0.943394  0.530759  0.239667  0.847559

[333 rows x 5 columns]

In [110]:
newdf.drop(['A','C'],axis=1)

            B         D         E
0    0.935295  0.389377  0.236715
1    0.139270  0.170881  0.299616
2    0.276038  0.922318  0.509565
3    0.849374  0.221360  0.357193
4    0.549811  0.162912  0.835231
..        ...       ...       ...
329  0.971063  0.672985  0.580792
330  0.309182  0.574723  0.475547
331  0.015571  0.144200  0.932766
332  0.185251  0.915528  0.011104
333  0.943394  0.239667  0.847559

[334 rows x 3 columns]

In [111]:
newdf.drop(['D','E'],axis=1, inplace=True)

In [112]:
newdf

            A         B         C
0         980  0.935295  0.586612
1    0.991158  0.139270  0.814556
2    0.943957  0.276038  0.841544
3    0.585182  0.849374  0.489625
4    0.254445  0.549811  0.463228
..        ...       ...       ...
329  0.983074  0.971063  0.946773
330  0.733364  0.309182  0.665807
331  0.280746  0.015571  0.093510
332  0.985685  0.185251  0.985174
333   0.24603  0.943394  0.530759

[334 rows x 3 columns]

In [113]:
newdf.reset_index(drop=True, inplace=True)
newdf.head(3)

          A         B         C
0       980  0.935295  0.586612
1  0.991158  0.139270  0.814556
2  0.943957  0.276038  0.841544

In [114]:
newdf['B']=None